name: Continuous Delivery

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps

      - name: Build
        run: |
          npm run build
